### ISSUE TITLE
Issue trying to publish a page when using PostgreSQL

### ISSUE THREAD

**Issue by cybersimon** [bashu/fluentcms-publishing#4]
e.g.
![screen shot 2017-02-08 at 12 39 14 pm](https://cloud.githubusercontent.com/assets/1009151/22719849/a43b0e54-edfb-11e6-80cd-4c79992b4d7c.png)

The issue is here:
fluentcms_publishing/admin.py in get_model_object

**Comment by bashu** [comment]
closed via @f3fbe7d312235c6b4d858bdb333bdedbf09df0e8
